language: java
jobs:
  include:
    - stage: deploy monitor and datawarehouse
      script: skip
      deploy: &heroku
        provider: heroku
        api_key:
          secure: $HEROKU_AUTH_TOKEN
        app: smart-city-server
    - stage: deploy update and event-emitter
      script: skip
      deploy:
        <<: *heroku
        app: smart-city-updater